// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA54tDRdbcQzY4ZdDabGaSd-KRR0C5Mzio',
    appId: '1:47428278627:web:0ef2fa65e9e311eccf9b56',
    messagingSenderId: '47428278627',
    projectId: 'burki-book',
    authDomain: 'burki-book.firebaseapp.com',
    storageBucket: 'burki-book.firebasestorage.app',
    measurementId: 'G-WCW2VNVQ0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3tfmJs2gmdT0CkeHcBKnrBTCe6khrZ4E',
    appId: '1:47428278627:android:51fc90957b585d8ecf9b56',
    messagingSenderId: '47428278627',
    projectId: 'burki-book',
    storageBucket: 'burki-book.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7v4yAtlh7Kn4sGV01xxIKRa8ZQntI6Y',
    appId: '1:47428278627:ios:03d62ec3c7872cbacf9b56',
    messagingSenderId: '47428278627',
    projectId: 'burki-book',
    storageBucket: 'burki-book.firebasestorage.app',
    iosBundleId: 'com.example.burkiBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB7v4yAtlh7Kn4sGV01xxIKRa8ZQntI6Y',
    appId: '1:47428278627:ios:03d62ec3c7872cbacf9b56',
    messagingSenderId: '47428278627',
    projectId: 'burki-book',
    storageBucket: 'burki-book.firebasestorage.app',
    iosBundleId: 'com.example.burkiBook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA54tDRdbcQzY4ZdDabGaSd-KRR0C5Mzio',
    appId: '1:47428278627:web:7ddb3a3726722111cf9b56',
    messagingSenderId: '47428278627',
    projectId: 'burki-book',
    authDomain: 'burki-book.firebaseapp.com',
    storageBucket: 'burki-book.firebasestorage.app',
    measurementId: 'G-XKDH52F786',
  );
}
